import './globals.css'

import Header from './index/Header'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " flex flex-col"}>
        <Header />
        <main className="grow pt-5 px-12 justify-between background bg-slate-900 overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  )
}
